appname: sample
port: 8000

db:
    use: mysql
    mysql:
        -   enabled: false
            host: xx.xx.xx.xxx
            port: xxxx
            username: xxxxxx
            password: xxxxxxxxxx
            database: xxxxxxxxxx
            nameconn: connMysql
    postgres:
        -   enabled: true
            host: xx.xx.xx.xxx
            port: xxxx
            username: xxxxxx
            password: xxxxxxxxxx
            database: xxxxxxxxxx
            nameconn: connPostgres

contacts:
    name: 'Javier Lecca'
    email: leccajavier@gmail.com